#!name=Google搜索重定向
#!desc=将Google搜索重定向至.com域名，如遇频繁跳转请禁用本插件。
#!author=可莉🅥
#!icon=https://gitlab.com/lodepuly/iconlibrary/-/raw/main/App_icon/120px/Google.png
#!homepage=https://gitlab.com/lodepuly/vpn_tool/-/tree/master/Tool/Loon/Plugin
#!date=2023-11-14 14:41:32

[URL Rewrite]
# ^https?:\/\/(www.)?(g|google)\.(cn|com\.hk) 302 https://www.google.com
^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302
^https?:\/\/(ditu|maps).google\.cn https://maps.google.com 302

[MITM]
hostname = %APPEND% www.google.cn
